name: Daily

on:
  schedule:
    - cron: '00 15 * * *'

  workflow_dispatch:

permissions:
  contents: write

jobs:  
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: |
          echo "YEAR=`date "+%Y"`" >> $GITHUB_ENV
          echo "MONTH=`date "+%m"`" >> $GITHUB_ENV
          echo "DAY=`date "+%d"`" >> $GITHUB_ENV
      - name: Create new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git pull origin daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }} || true
          git switch daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }} || git switch -c daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }}
          git push -u origin daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }}
      - run: nimble install https://github.com/momeemt/monokaki -y
      - run: monokaki build
      - name: Generate Daily
        run: monokaki new:daily
      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: daily/${{ env.YEAR }}-${{ env.MONTH }}-${{ env.DAY }}
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "✏️ Add: ${{ env.YEAR }}.${{ env.MONTH }}.${{ env.DAY }}"